import {inspectMp4} from './mp4.js';
import {FFmpeg} from '@ffmpeg/ffmpeg';
import {argumentsFor,parentOrigin} from './convert.js';
import './style.css';
const query=new URLSearchParams(location.search),origin=parentOrigin(query.get('parent')),channel=query.get('channel');
let language=query.get('lang')==='en'?'en':'zh',file=null,result=null,engine=null,busy=false,job=0,sourceURL='',resultURL='';
const t=(zh,en)=>language==='en'?en:zh;
document.querySelector('#app').innerHTML=`<header><span class="brand">SHOW CHAMP <b>CONVERTER</b></span><select id="language" aria-label="Language / 语言"><option value="zh">中文</option><option value="en">English</option></select></header><section class="intro"><span class="eyebrow">H.264 MP4 · AAC</span><h1>${t('把视频，变成可以发布的样子。','Make your video ready to share.')}</h1><p>${t('在本机裁剪和转换，完成后预览、下载或返回秀场。','Trim and convert on your device. Preview, download or return to Show Champ.')}</p></section><section class="card"><label class="file-label">${t('选择视频 · 原文件最多100MB','Choose video · Source up to 100MB')}<input id="file" type="file" accept="video/*,.mov,.mp4,.mkv,.avi,.webm,.m4v,.flv,.mpeg,.mpg,.3gp,.ts"/></label><p id="filename" class="muted"></p><video id="source" controls playsinline preload="metadata" hidden></video><p class="muted">${t('原片无法预览时仍可尝试转换。手机建议先处理较短片段。','Conversion can work even if source preview fails. Try a short clip on phones.')}</p><div class="settings"><label>${t('起点（秒）','Start (seconds)')}<input id="start" type="number" min="0" step="0.1" value="0"/></label><label>${t('截取时长（最多60秒）','Clip duration (up to 60 seconds)')}<input id="duration" type="number" min="0.1" max="60" step="0.1" value="30"/></label><label>${t('压缩画质','Quality')}<select id="quality"><option value="standard">${t('标准','Standard')}</option><option value="clear">${t('清晰','Clear')}</option><option value="small">${t('省流','Data saver')}</option></select></label></div><div class="actions"><button id="convert" class="primary" disabled>${t('转换并生成预览','Convert and preview')}</button><button id="cancel" hidden>${t('取消处理','Cancel')}</button></div><progress id="progress" max="100" value="0" hidden></progress><p id="status" role="status"></p><p id="error" role="alert"></p></section><section id="output" class="card" hidden><h2>${t('最终预览','Final preview')}</h2><video id="result" controls playsinline></video><p id="size" class="muted"></p><div class="actions"><a id="download" class="primary" download="show-champ-video.mp4">${t('下载 MP4','Download MP4')}</a><button id="return" hidden>${t('使用这个视频，返回秀场','Use this video in Show Champ')}</button></div></section><footer>${t('视频在本机处理。部分编码、损坏文件或大文件可能无法转换；转换期间请保持页面打开。','Files are processed locally. Some codecs, damaged or large files may fail. Keep this page open during conversion.')}<br/>${t('基于开源 ffmpeg.wasm / FFmpeg；首次使用需要加载转换组件。','Powered by open-source ffmpeg.wasm / FFmpeg. The engine loads on first use.')}</footer>`;
const $=id=>document.getElementById(id);
$('language').value=language;$('language').onchange=e=>{query.set('lang',e.target.value);location.search=query.toString();};
function message(text){$('status').textContent=text;}
function resetOutput(){result=null;$('output').hidden=true;if(resultURL)URL.revokeObjectURL(resultURL);resultURL='';}
function choose(value){if(busy)return;resetOutput();file=value;$('error').textContent='';$('filename').textContent=file?file.name+' · '+(file.size/1048576).toFixed(1)+' MB':'';if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL='';$('source').hidden=true;if(file?.size>100*1048576){file=null;$('error').textContent=t('原片超过100MB，请先剪短。','Source exceeds 100MB. Trim it first.');}if(file){sourceURL=URL.createObjectURL(file);$('source').src=sourceURL;$('source').hidden=false;}$('start').value=0;$('duration').value=30;$('convert').disabled=!file;message('');}
$('file').onchange=e=>choose(e.target.files[0]);
$('source').onloadedmetadata=()=>{const duration=$('source').duration;if(Number.isFinite(duration)&&duration>0)$('duration').value=Math.max(0.1,Math.min(60,duration)).toFixed(1);};
$('source').onerror=()=>message(t('原片预览不可用，仍可尝试下方转换。','Source preview is unavailable; you can still try conversion.'));
for(const id of ['start','duration','quality'])$(id).onchange=()=>resetOutput();
function state(value){busy=value;$('convert').disabled=value||!file;$('cancel').hidden=!value;for(const id of ['file','start','duration','quality','language'])$(id).disabled=value;$('progress').hidden=!value;}
async function loadCore(current){
 const ffmpeg=new FFmpeg();engine=ffmpeg;
 ffmpeg.on('progress',({progress})=>{if(current===job){$('progress').value=Math.max(0,Math.min(99,progress*100));message(t('正在转换，请保持页面打开…','Converting; keep this page open…'));}});
 message(t('首次加载转换组件，请稍候…','Loading the conversion engine…'));
 const manifest=await fetch('/core/manifest.json').then(r=>{if(!r.ok)throw Error('core');return r.json();});const parts=[];
 for(let i=0;i<manifest.parts.length;i++){const response=await fetch('/core/'+manifest.parts[i]);if(!response.ok)throw Error('core');parts.push(await response.arrayBuffer());if(current!==job)throw Error('cancelled');message(t('加载转换组件：','Loading engine: ')+Math.round((i+1)/manifest.parts.length*100)+'%');}
 const wasmURL=URL.createObjectURL(new Blob(parts,{type:'application/wasm'}));
 try{await ffmpeg.load({coreURL:new URL('/core/ffmpeg-core.js',location.origin).href,wasmURL});}finally{URL.revokeObjectURL(wasmURL);}
 return ffmpeg;
}
$('convert').onclick=async()=>{
 const current=++job;resetOutput();$('error').textContent='';let ffmpeg;
 try{const args=argumentsFor({start:Number($('start').value),duration:Number($('duration').value),quality:$('quality').value});state(true);ffmpeg=await loadCore(current);if(current!==job)return;message(t('正在读取原片…','Reading source…'));await ffmpeg.writeFile('input',new Uint8Array(await file.arrayBuffer()));if(current!==job)return;const code=await ffmpeg.exec(args,300000);if(current!==job)return;if(code!==0)throw Error('convert');const data=await ffmpeg.readFile('output.mp4');if(!data.length)throw Error('convert');if(data.length>20*1048576)throw Error('too_large');inspectMp4(data);result=new File([data],'show-champ-video.mp4',{type:'video/mp4'});resultURL=URL.createObjectURL(result);$('result').src=resultURL;$('download').href=resultURL;$('size').textContent='H.264 MP4 · AAC · '+(result.size/1048576).toFixed(2)+' MB';$('return').hidden=!origin||!channel||window.parent===window;$('output').hidden=false;message(t('转换完成，请检查预览后使用。','Conversion complete. Check the preview before using it.'));
 }catch(error){if(current===job)$('error').textContent=error.message==='invalid_settings'?t('起点需≥0，截取时长需在0–60秒之间。','Start must be at least 0; duration must be between 0 and 60 seconds.'):error.message==='too_large'?t('成品超过20MB，请缩短时间或选择省流画质。','Output exceeds 20MB. Shorten the clip or select data saver.'):t('转换未成功，可能是文件编码、内存不足或加载失败。请试较短片段，并用 Safari/Chrome 直接打开网页重试。','Conversion failed: unsupported encoding, insufficient memory or engine load failure. Try a shorter clip in Safari/Chrome.');
 }finally{ffmpeg?.terminate();if(current===job){engine=null;state(false);}}
};
$('cancel').onclick=()=>{job++;engine?.terminate();engine=null;state(false);message(t('已取消处理。','Conversion canceled.'));};
$('return').onclick=()=>{if(result&&origin&&channel){window.parent.postMessage({type:'show-champ-converted',channel,file:result},origin);message(t('已发送到秀场，请在发布页确认预览。','Sent to Show Champ. Confirm the preview in the publishing page.'));}};
window.addEventListener('message',event=>{if(event.origin!==origin||event.source!==window.parent||event.data?.channel!==channel||event.data.type!=='show-champ-source'||!(event.data.file instanceof Blob))return;choose(new File([event.data.file],event.data.file.name||'source-video',{type:event.data.file.type}));});
if(origin&&channel&&window.parent!==window)window.parent.postMessage({type:'show-champ-converter-ready',channel},origin);
